// Generated by tsbindgen - Architecture
// Namespace: Microsoft.VisualBasic.FileIO
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.VisualBasic.FileIO/internal/index.js';

// Cross-namespace type imports for constraints
import type { ReadOnlyCollection_1 } from './System.Collections.ObjectModel/internal/index.js';
import type { IDictionary } from './System.Collections/internal/index.js';
import type { DirectoryInfo, DriveInfo, FileInfo, Stream, StreamReader, StreamWriter, TextReader } from './System.IO/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Encoding } from './System.Text/internal/index.js';
import type { Boolean as ClrBoolean, Byte, Enum, Exception, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { FileSystem as FileSystem } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { DeleteDirectoryOption as DeleteDirectoryOption } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { RecycleOption as RecycleOption } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { SearchOption as SearchOption } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { UICancelOption as UICancelOption } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { UIOption as UIOption } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { MalformedLineException as MalformedLineException } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { SpecialDirectories as SpecialDirectories } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { TextFieldParser as TextFieldParser } from './Microsoft.VisualBasic.FileIO/internal/index.js';
export { FieldType as FieldType } from './Microsoft.VisualBasic.FileIO/internal/index.js';
