// Generated by tsbindgen - Architecture
// Namespace: System.Diagnostics.Tracing
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Diagnostics.Tracing/internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary_2, IEnumerable_1 } from './System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from './System.Collections.ObjectModel/internal/index.js';
import type { IDictionary } from './System.Collections/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Attribute, Boolean as ClrBoolean, Byte, DateTime, Double, Enum, EventArgs, EventHandler_1, Exception, Func_1, Guid, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, Single, String as ClrString, TimeSpan, Type, TypeCode, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DiagnosticCounter as DiagnosticCounter } from './System.Diagnostics.Tracing/internal/index.js';
export { EventActivityOptions as EventActivityOptions } from './System.Diagnostics.Tracing/internal/index.js';
export { EventCounter as EventCounter } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSource as EventSource } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSource_EventSourcePrimitive as EventSource_EventSourcePrimitive } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSourceSettings as EventSourceSettings } from './System.Diagnostics.Tracing/internal/index.js';
export { EventListener as EventListener } from './System.Diagnostics.Tracing/internal/index.js';
export { EventCommandEventArgs as EventCommandEventArgs } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSourceCreatedEventArgs as EventSourceCreatedEventArgs } from './System.Diagnostics.Tracing/internal/index.js';
export { EventWrittenEventArgs as EventWrittenEventArgs } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSourceAttribute as EventSourceAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { EventAttribute as EventAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { NonEventAttribute as NonEventAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { EventCommand as EventCommand } from './System.Diagnostics.Tracing/internal/index.js';
export { EventManifestOptions as EventManifestOptions } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSourceException as EventSourceException } from './System.Diagnostics.Tracing/internal/index.js';
export { IncrementingEventCounter as IncrementingEventCounter } from './System.Diagnostics.Tracing/internal/index.js';
export { IncrementingPollingCounter as IncrementingPollingCounter } from './System.Diagnostics.Tracing/internal/index.js';
export { PollingCounter as PollingCounter } from './System.Diagnostics.Tracing/internal/index.js';
export { EventLevel as EventLevel } from './System.Diagnostics.Tracing/internal/index.js';
export { EventTask as EventTask } from './System.Diagnostics.Tracing/internal/index.js';
export { EventOpcode as EventOpcode } from './System.Diagnostics.Tracing/internal/index.js';
export { EventChannel as EventChannel } from './System.Diagnostics.Tracing/internal/index.js';
export { EventKeywords as EventKeywords } from './System.Diagnostics.Tracing/internal/index.js';
export { EventDataAttribute as EventDataAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { EventFieldTags as EventFieldTags } from './System.Diagnostics.Tracing/internal/index.js';
export { EventFieldAttribute as EventFieldAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { EventFieldFormat as EventFieldFormat } from './System.Diagnostics.Tracing/internal/index.js';
export { EventIgnoreAttribute as EventIgnoreAttribute } from './System.Diagnostics.Tracing/internal/index.js';
export { EventSourceOptions as EventSourceOptions } from './System.Diagnostics.Tracing/internal/index.js';
export { EventTags as EventTags } from './System.Diagnostics.Tracing/internal/index.js';
