// Generated by tsbindgen - Architecture
// Namespace: System.Text.Json.Serialization
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Text.Json.Serialization/internal/index.js';

// Cross-namespace type imports for constraints
import type { IJsonTypeInfoResolver, JsonTypeInfo } from './System.Text.Json.Serialization.Metadata/internal/index.js';
import type { JsonCommentHandling, JsonNamingPolicy, JsonSerializerDefaults, JsonSerializerOptions, Utf8JsonReader, Utf8JsonWriter } from './System.Text.Json/internal/index.js';
import type { Attribute, Boolean as ClrBoolean, Char, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { JsonAttribute as JsonAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonIgnoreCondition as JsonIgnoreCondition } from './System.Text.Json.Serialization/internal/index.js';
export { JsonKnownNamingPolicy as JsonKnownNamingPolicy } from './System.Text.Json.Serialization/internal/index.js';
export { JsonKnownReferenceHandler as JsonKnownReferenceHandler } from './System.Text.Json.Serialization/internal/index.js';
export { JsonNumberHandling as JsonNumberHandling } from './System.Text.Json.Serialization/internal/index.js';
export { JsonObjectCreationHandling as JsonObjectCreationHandling } from './System.Text.Json.Serialization/internal/index.js';
export { JsonSerializableAttribute as JsonSerializableAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonSourceGenerationMode as JsonSourceGenerationMode } from './System.Text.Json.Serialization/internal/index.js';
export { JsonSourceGenerationOptionsAttribute as JsonSourceGenerationOptionsAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonUnknownTypeHandling as JsonUnknownTypeHandling } from './System.Text.Json.Serialization/internal/index.js';
export { JsonUnmappedMemberHandling as JsonUnmappedMemberHandling } from './System.Text.Json.Serialization/internal/index.js';
export { JsonObjectCreationHandlingAttribute as JsonObjectCreationHandlingAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonConstructorAttribute as JsonConstructorAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonConverterAttribute as JsonConverterAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonDerivedTypeAttribute as JsonDerivedTypeAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonExtensionDataAttribute as JsonExtensionDataAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonIgnoreAttribute as JsonIgnoreAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonIncludeAttribute as JsonIncludeAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonNumberHandlingAttribute as JsonNumberHandlingAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonPolymorphicAttribute as JsonPolymorphicAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonPropertyNameAttribute as JsonPropertyNameAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonRequiredAttribute as JsonRequiredAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonPropertyOrderAttribute as JsonPropertyOrderAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { JsonUnmappedMemberHandlingAttribute as JsonUnmappedMemberHandlingAttribute } from './System.Text.Json.Serialization/internal/index.js';
export type IJsonOnDeserialized = Internal.IJsonOnDeserialized;
export type IJsonOnDeserializing = Internal.IJsonOnDeserializing;
export type IJsonOnSerialized = Internal.IJsonOnSerialized;
export type IJsonOnSerializing = Internal.IJsonOnSerializing;
export { JsonNumberEnumConverter_1 as JsonNumberEnumConverter } from './System.Text.Json.Serialization/internal/index.js';
export { JsonSerializerContext as JsonSerializerContext } from './System.Text.Json.Serialization/internal/index.js';
export { JsonUnknownDerivedTypeHandling as JsonUnknownDerivedTypeHandling } from './System.Text.Json.Serialization/internal/index.js';
export { JsonConverter as JsonConverter_0 } from './System.Text.Json.Serialization/internal/index.js';
export { JsonConverterFactory as JsonConverterFactory } from './System.Text.Json.Serialization/internal/index.js';
export { JsonConverter_1 as JsonConverter } from './System.Text.Json.Serialization/internal/index.js';
export { JsonStringEnumConverter_1 as JsonStringEnumConverter } from './System.Text.Json.Serialization/internal/index.js';
export { JsonStringEnumConverter as JsonStringEnumConverter_0 } from './System.Text.Json.Serialization/internal/index.js';
export { JsonStringEnumMemberNameAttribute as JsonStringEnumMemberNameAttribute } from './System.Text.Json.Serialization/internal/index.js';
export { ReferenceHandler as ReferenceHandler_0 } from './System.Text.Json.Serialization/internal/index.js';
export { ReferenceHandler_1 as ReferenceHandler } from './System.Text.Json.Serialization/internal/index.js';
export { ReferenceResolver as ReferenceResolver } from './System.Text.Json.Serialization/internal/index.js';
