// Generated by tsbindgen - Architecture
// Namespace: System.Security.AccessControl
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.AccessControl/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection, IDictionary, IEnumerable, IEnumerator, ReadOnlyCollectionBase } from './System.Collections/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { IdentityReference, SecurityIdentifier } from './System.Security.Principal/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Enum, Exception, Guid, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, UnauthorizedAccessException, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { RegistryAccessRule as RegistryAccessRule } from './System.Security.AccessControl/internal/index.js';
export { RegistryAuditRule as RegistryAuditRule } from './System.Security.AccessControl/internal/index.js';
export { RegistryRights as RegistryRights } from './System.Security.AccessControl/internal/index.js';
export { RegistrySecurity as RegistrySecurity } from './System.Security.AccessControl/internal/index.js';
export { DirectoryObjectSecurity as DirectoryObjectSecurity } from './System.Security.AccessControl/internal/index.js';
export { DirectorySecurity as DirectorySecurity } from './System.Security.AccessControl/internal/index.js';
export { FileSecurity as FileSecurity } from './System.Security.AccessControl/internal/index.js';
export { FileSystemAccessRule as FileSystemAccessRule } from './System.Security.AccessControl/internal/index.js';
export { FileSystemAuditRule as FileSystemAuditRule } from './System.Security.AccessControl/internal/index.js';
export { FileSystemRights as FileSystemRights } from './System.Security.AccessControl/internal/index.js';
export { FileSystemSecurity as FileSystemSecurity } from './System.Security.AccessControl/internal/index.js';
export { AccessControlActions as AccessControlActions } from './System.Security.AccessControl/internal/index.js';
export { AccessControlModification as AccessControlModification } from './System.Security.AccessControl/internal/index.js';
export { AccessControlSections as AccessControlSections } from './System.Security.AccessControl/internal/index.js';
export { AccessControlType as AccessControlType } from './System.Security.AccessControl/internal/index.js';
export { AccessRule as AccessRule_0 } from './System.Security.AccessControl/internal/index.js';
export { AccessRule_1 as AccessRule } from './System.Security.AccessControl/internal/index.js';
export { AceEnumerator as AceEnumerator } from './System.Security.AccessControl/internal/index.js';
export { AceFlags as AceFlags } from './System.Security.AccessControl/internal/index.js';
export { AceQualifier as AceQualifier } from './System.Security.AccessControl/internal/index.js';
export { AceType as AceType } from './System.Security.AccessControl/internal/index.js';
export { AuditFlags as AuditFlags } from './System.Security.AccessControl/internal/index.js';
export { AuditRule as AuditRule_0 } from './System.Security.AccessControl/internal/index.js';
export { AuditRule_1 as AuditRule } from './System.Security.AccessControl/internal/index.js';
export { AuthorizationRule as AuthorizationRule } from './System.Security.AccessControl/internal/index.js';
export { AuthorizationRuleCollection as AuthorizationRuleCollection } from './System.Security.AccessControl/internal/index.js';
export { CommonAce as CommonAce } from './System.Security.AccessControl/internal/index.js';
export { CommonAcl as CommonAcl } from './System.Security.AccessControl/internal/index.js';
export { CommonObjectSecurity as CommonObjectSecurity } from './System.Security.AccessControl/internal/index.js';
export { CommonSecurityDescriptor as CommonSecurityDescriptor } from './System.Security.AccessControl/internal/index.js';
export { CompoundAce as CompoundAce } from './System.Security.AccessControl/internal/index.js';
export { CompoundAceType as CompoundAceType } from './System.Security.AccessControl/internal/index.js';
export { ControlFlags as ControlFlags } from './System.Security.AccessControl/internal/index.js';
export { CustomAce as CustomAce } from './System.Security.AccessControl/internal/index.js';
export { DiscretionaryAcl as DiscretionaryAcl } from './System.Security.AccessControl/internal/index.js';
export { GenericAce as GenericAce } from './System.Security.AccessControl/internal/index.js';
export { GenericAcl as GenericAcl } from './System.Security.AccessControl/internal/index.js';
export { GenericSecurityDescriptor as GenericSecurityDescriptor } from './System.Security.AccessControl/internal/index.js';
export { InheritanceFlags as InheritanceFlags } from './System.Security.AccessControl/internal/index.js';
export { KnownAce as KnownAce } from './System.Security.AccessControl/internal/index.js';
export { NativeObjectSecurity as NativeObjectSecurity } from './System.Security.AccessControl/internal/index.js';
export { ObjectAccessRule as ObjectAccessRule } from './System.Security.AccessControl/internal/index.js';
export { ObjectAce as ObjectAce } from './System.Security.AccessControl/internal/index.js';
export { ObjectAceFlags as ObjectAceFlags } from './System.Security.AccessControl/internal/index.js';
export { ObjectAuditRule as ObjectAuditRule } from './System.Security.AccessControl/internal/index.js';
export { ObjectSecurity as ObjectSecurity_0 } from './System.Security.AccessControl/internal/index.js';
export { ObjectSecurity_1 as ObjectSecurity } from './System.Security.AccessControl/internal/index.js';
export { PrivilegeNotHeldException as PrivilegeNotHeldException } from './System.Security.AccessControl/internal/index.js';
export { PropagationFlags as PropagationFlags } from './System.Security.AccessControl/internal/index.js';
export { QualifiedAce as QualifiedAce } from './System.Security.AccessControl/internal/index.js';
export { RawAcl as RawAcl } from './System.Security.AccessControl/internal/index.js';
export { RawSecurityDescriptor as RawSecurityDescriptor } from './System.Security.AccessControl/internal/index.js';
export { ResourceType as ResourceType } from './System.Security.AccessControl/internal/index.js';
export { SecurityInfos as SecurityInfos } from './System.Security.AccessControl/internal/index.js';
export { SystemAcl as SystemAcl } from './System.Security.AccessControl/internal/index.js';
export { EventWaitHandleAccessRule as EventWaitHandleAccessRule } from './System.Security.AccessControl/internal/index.js';
export { EventWaitHandleAuditRule as EventWaitHandleAuditRule } from './System.Security.AccessControl/internal/index.js';
export { EventWaitHandleRights as EventWaitHandleRights } from './System.Security.AccessControl/internal/index.js';
export { EventWaitHandleSecurity as EventWaitHandleSecurity } from './System.Security.AccessControl/internal/index.js';
export { MutexAccessRule as MutexAccessRule } from './System.Security.AccessControl/internal/index.js';
export { MutexAuditRule as MutexAuditRule } from './System.Security.AccessControl/internal/index.js';
export { MutexRights as MutexRights } from './System.Security.AccessControl/internal/index.js';
export { MutexSecurity as MutexSecurity } from './System.Security.AccessControl/internal/index.js';
export { SemaphoreAccessRule as SemaphoreAccessRule } from './System.Security.AccessControl/internal/index.js';
export { SemaphoreAuditRule as SemaphoreAuditRule } from './System.Security.AccessControl/internal/index.js';
export { SemaphoreRights as SemaphoreRights } from './System.Security.AccessControl/internal/index.js';
export { SemaphoreSecurity as SemaphoreSecurity } from './System.Security.AccessControl/internal/index.js';
