// Generated by tsbindgen - Architecture
// Namespace: System.Security.Principal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.Principal/internal/index.js';

// Cross-namespace type imports for constraints
import type { SafeAccessTokenHandle } from './Microsoft.Win32.SafeHandles/internal/index.js';
import type { ICollection_1, IEnumerable_1, IEnumerator_1 } from './System.Collections.Generic/internal/index.js';
import type { IDictionary, IEnumerable, IEnumerator } from './System.Collections/internal/index.js';
import type { BinaryWriter } from './System.IO/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { IDeserializationCallback, ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Claim, ClaimsIdentity, ClaimsPrincipal } from './System.Security.Claims/internal/index.js';
import type { Task, Task_1 } from './System.Threading.Tasks/internal/index.js';
import type { Action, Boolean as ClrBoolean, Byte, Enum, Exception, Func_1, IComparable, IComparable_1, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, IntPtr, ISpanFormattable, Object as ClrObject, Predicate_1, String as ClrString, SystemException, Type, TypeCode, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export type IIdentity = Internal.IIdentity;
export type IPrincipal = Internal.IPrincipal;
export { PrincipalPolicy as PrincipalPolicy } from './System.Security.Principal/internal/index.js';
export { TokenImpersonationLevel as TokenImpersonationLevel } from './System.Security.Principal/internal/index.js';
export { GenericIdentity as GenericIdentity } from './System.Security.Principal/internal/index.js';
export { GenericPrincipal as GenericPrincipal } from './System.Security.Principal/internal/index.js';
export { IdentityNotMappedException as IdentityNotMappedException } from './System.Security.Principal/internal/index.js';
export { IdentityReference as IdentityReference } from './System.Security.Principal/internal/index.js';
export { IdentityReferenceCollection as IdentityReferenceCollection } from './System.Security.Principal/internal/index.js';
export { NTAccount as NTAccount } from './System.Security.Principal/internal/index.js';
export { SecurityIdentifier as SecurityIdentifier } from './System.Security.Principal/internal/index.js';
export { TokenAccessLevels as TokenAccessLevels } from './System.Security.Principal/internal/index.js';
export { WellKnownSidType as WellKnownSidType } from './System.Security.Principal/internal/index.js';
export { WindowsAccountType as WindowsAccountType } from './System.Security.Principal/internal/index.js';
export { WindowsBuiltInRole as WindowsBuiltInRole } from './System.Security.Principal/internal/index.js';
export { WindowsIdentity as WindowsIdentity } from './System.Security.Principal/internal/index.js';
export { WindowsPrincipal as WindowsPrincipal } from './System.Security.Principal/internal/index.js';
