// Generated by tsbindgen - Architecture
// Namespace: System.Security.Permissions
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.Permissions/internal/index.js';

// Cross-namespace type imports for constraints
import type { IPermission } from './System.Security/internal/index.js';
import type { Attribute, Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CodeAccessSecurityAttribute as CodeAccessSecurityAttribute } from './System.Security.Permissions/internal/index.js';
export { PermissionState as PermissionState } from './System.Security.Permissions/internal/index.js';
export { SecurityAction as SecurityAction } from './System.Security.Permissions/internal/index.js';
export { SecurityAttribute as SecurityAttribute } from './System.Security.Permissions/internal/index.js';
export { SecurityPermissionAttribute as SecurityPermissionAttribute } from './System.Security.Permissions/internal/index.js';
export { SecurityPermissionFlag as SecurityPermissionFlag } from './System.Security.Permissions/internal/index.js';
