// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.InteropServices.Java
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace System.Runtime.InteropServices.Java in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
