// Generated by tsbindgen - Architecture
// Namespace: System.Threading.Tasks.Sources
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace System.Threading.Tasks.Sources in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
