// Generated by tsbindgen - Architecture
// Namespace: System.Text.Json.Schema
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace System.Text.Json.Schema in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
