// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Serialization.Formatters.Binary
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Runtime.Serialization.Formatters.Binary/internal/index.js';

// Cross-namespace type imports for constraints
import type { Stream } from './System.IO/internal/index.js';
import type { FormatterAssemblyStyle, FormatterTypeStyle, TypeFilterLevel } from './System.Runtime.Serialization.Formatters/internal/index.js';
import type { IFormatter, ISurrogateSelector, SerializationBinder, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { BinaryFormatter as BinaryFormatter } from './System.Runtime.Serialization.Formatters.Binary/internal/index.js';
