// Generated by tsbindgen - Architecture
// Namespace: System.Net.Http
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Net.Http/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IReadOnlyCollection_1, IReadOnlyDictionary_2, KeyValuePair_2 } from './System.Collections.Generic/internal/index.js';
import type { IDictionary, IEnumerable, IEnumerator } from './System.Collections/internal/index.js';
import type { IMeterFactory } from './System.Diagnostics.Metrics/internal/index.js';
import type { DistributedContextPropagator } from './System.Diagnostics/internal/index.js';
import type { IOException, Stream } from './System.IO/internal/index.js';
import type { HttpContentHeaders, HttpRequestHeaders, HttpResponseHeaders, MediaTypeHeaderValue } from './System.Net.Http.Headers/internal/index.js';
import type { SslClientAuthenticationOptions, SslPolicyErrors } from './System.Net.Security/internal/index.js';
import type { CookieContainer, DecompressionMethods, DnsEndPoint, HttpStatusCode, ICredentials, IWebProxy, TransportContext } from './System.Net/internal/index.js';
import type { MethodBase, MethodInfo } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { SslProtocols } from './System.Security.Authentication/internal/index.js';
import type { X509Certificate2, X509CertificateCollection, X509Chain } from './System.Security.Cryptography.X509Certificates/internal/index.js';
import type { Encoding } from './System.Text/internal/index.js';
import type { Task, Task_1, ValueTask_1 } from './System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { AsyncCallback, Boolean as ClrBoolean, Byte, Char, Delegate, Enum, Exception, Func_3, Func_5, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IEquatable_1, IFormatProvider, IFormattable, Int32, Int64, IntPtr, ISpanFormattable, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, String as ClrString, TimeSpan, Type, TypeCode, Uri, ValueType, Version, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ByteArrayContent as ByteArrayContent } from './System.Net.Http/internal/index.js';
export { ClientCertificateOption as ClientCertificateOption } from './System.Net.Http/internal/index.js';
export { DelegatingHandler as DelegatingHandler } from './System.Net.Http/internal/index.js';
export { FormUrlEncodedContent as FormUrlEncodedContent } from './System.Net.Http/internal/index.js';
export type HeaderEncodingSelector<TContext> = Internal.HeaderEncodingSelector_1<TContext>;
export { HttpClient as HttpClient } from './System.Net.Http/internal/index.js';
export { HttpClientHandler as HttpClientHandler } from './System.Net.Http/internal/index.js';
export { HttpCompletionOption as HttpCompletionOption } from './System.Net.Http/internal/index.js';
export { HttpContent as HttpContent } from './System.Net.Http/internal/index.js';
export { HttpMessageHandler as HttpMessageHandler } from './System.Net.Http/internal/index.js';
export { HttpMessageInvoker as HttpMessageInvoker } from './System.Net.Http/internal/index.js';
export { HttpMethod as HttpMethod } from './System.Net.Http/internal/index.js';
export { HttpProtocolException as HttpProtocolException } from './System.Net.Http/internal/index.js';
export { HttpRequestException as HttpRequestException } from './System.Net.Http/internal/index.js';
export { HttpRequestError as HttpRequestError } from './System.Net.Http/internal/index.js';
export { HttpRequestMessage as HttpRequestMessage } from './System.Net.Http/internal/index.js';
export { HttpRequestOptions as HttpRequestOptions } from './System.Net.Http/internal/index.js';
export { HttpRequestOptionsKey_1 as HttpRequestOptionsKey } from './System.Net.Http/internal/index.js';
export { HttpResponseMessage as HttpResponseMessage } from './System.Net.Http/internal/index.js';
export { HttpIOException as HttpIOException } from './System.Net.Http/internal/index.js';
export { HttpVersionPolicy as HttpVersionPolicy } from './System.Net.Http/internal/index.js';
export { MessageProcessingHandler as MessageProcessingHandler } from './System.Net.Http/internal/index.js';
export { MultipartContent as MultipartContent } from './System.Net.Http/internal/index.js';
export { MultipartFormDataContent as MultipartFormDataContent } from './System.Net.Http/internal/index.js';
export { ReadOnlyMemoryContent as ReadOnlyMemoryContent } from './System.Net.Http/internal/index.js';
export { StreamContent as StreamContent } from './System.Net.Http/internal/index.js';
export { StringContent as StringContent } from './System.Net.Http/internal/index.js';
export { SocketsHttpPlaintextStreamFilterContext as SocketsHttpPlaintextStreamFilterContext } from './System.Net.Http/internal/index.js';
export { HttpKeepAlivePingPolicy as HttpKeepAlivePingPolicy } from './System.Net.Http/internal/index.js';
export { SocketsHttpConnectionContext as SocketsHttpConnectionContext } from './System.Net.Http/internal/index.js';
export { SocketsHttpHandler as SocketsHttpHandler } from './System.Net.Http/internal/index.js';
