// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Intrinsics.Arm
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Runtime.Intrinsics.Arm/internal/index.js';

// Cross-namespace type imports for constraints
import type { Vector_1 } from './System.Numerics/internal/index.js';
import type { Vector128_1, Vector64_1 } from './System.Runtime.Intrinsics/internal/index.js';
import type { Boolean as ClrBoolean, Byte, Double, Enum, IComparable, IConvertible, IFormatProvider, IFormattable, Int16, Int32, Int64, ISpanFormattable, Object as ClrObject, SByte, Single, String as ClrString, Type, TypeCode, UInt16, UInt32, UInt64, ValueTuple_2, ValueTuple_3, ValueTuple_4, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SveMaskPattern as SveMaskPattern } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { SvePrefetchType as SvePrefetchType } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { AdvSimd as AdvSimd } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { AdvSimd_Arm64 as AdvSimd_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Aes as Aes } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Aes_Arm64 as Aes_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { ArmBase as ArmBase } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { ArmBase_Arm64 as ArmBase_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Crc32 as Crc32 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Crc32_Arm64 as Crc32_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Dp as Dp } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Dp_Arm64 as Dp_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Rdm as Rdm } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Rdm_Arm64 as Rdm_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sha1 as Sha1 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sha1_Arm64 as Sha1_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sha256 as Sha256 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sha256_Arm64 as Sha256_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sve as Sve } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sve_Arm64 as Sve_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sve2 as Sve2 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
export { Sve2_Arm64 as Sve2_Arm64 } from './System.Runtime.Intrinsics.Arm/internal/index.js';
