// Generated by tsbindgen - Architecture
// Namespace: System.Threading.Channels
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Threading.Channels/internal/index.js';

// Cross-namespace type imports for constraints
import type { IAsyncEnumerable_1, IComparer_1 } from './System.Collections.Generic/internal/index.js';
import type { IDictionary } from './System.Collections/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Task, ValueTask, ValueTask_1 } from './System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { Action_1, Boolean as ClrBoolean, Enum, Exception, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, InvalidOperationException, ISpanFormattable, Object as ClrObject, String as ClrString, Type, TypeCode, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { BoundedChannelFullMode as BoundedChannelFullMode } from './System.Threading.Channels/internal/index.js';
export { Channel$instance as Channel_0 } from './System.Threading.Channels/internal/index.js';
export { ChannelClosedException as ChannelClosedException } from './System.Threading.Channels/internal/index.js';
export { ChannelOptions as ChannelOptions } from './System.Threading.Channels/internal/index.js';
export { BoundedChannelOptions as BoundedChannelOptions } from './System.Threading.Channels/internal/index.js';
export { UnboundedChannelOptions as UnboundedChannelOptions } from './System.Threading.Channels/internal/index.js';
export { ChannelReader_1 as ChannelReader } from './System.Threading.Channels/internal/index.js';
export { ChannelWriter_1 as ChannelWriter } from './System.Threading.Channels/internal/index.js';
export { Channel_1 as Channel } from './System.Threading.Channels/internal/index.js';
export { UnboundedPrioritizedChannelOptions_1 as UnboundedPrioritizedChannelOptions } from './System.Threading.Channels/internal/index.js';
