// Generated by tsbindgen - Architecture
// Namespace: System.IO.Compression
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.IO.Compression/internal/index.js';

// Cross-namespace type imports for constraints
import type { OperationStatus } from './System.Buffers/internal/index.js';
import type { ReadOnlyCollection_1 } from './System.Collections.ObjectModel/internal/index.js';
import type { IDictionary } from './System.Collections/internal/index.js';
import type { IOException, SeekOrigin, Stream } from './System.IO/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Encoding } from './System.Text/internal/index.js';
import type { Task, Task_1, ValueTask, ValueTask_1 } from './System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { AsyncCallback, Boolean as ClrBoolean, Byte, DateTimeOffset, Enum, Exception, IAsyncDisposable, IAsyncResult, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Memory_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Span_1, String as ClrString, Type, TypeCode, UInt32, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ZipArchive as ZipArchive } from './System.IO.Compression/internal/index.js';
export { ZipArchiveEntry as ZipArchiveEntry } from './System.IO.Compression/internal/index.js';
export { ZipArchiveMode as ZipArchiveMode } from './System.IO.Compression/internal/index.js';
export { DeflateStream as DeflateStream } from './System.IO.Compression/internal/index.js';
export { ZLibException as ZLibException } from './System.IO.Compression/internal/index.js';
export { CompressionLevel as CompressionLevel } from './System.IO.Compression/internal/index.js';
export { CompressionMode as CompressionMode } from './System.IO.Compression/internal/index.js';
export { GZipStream as GZipStream } from './System.IO.Compression/internal/index.js';
export { ZLibCompressionOptions as ZLibCompressionOptions } from './System.IO.Compression/internal/index.js';
export { ZLibCompressionStrategy as ZLibCompressionStrategy } from './System.IO.Compression/internal/index.js';
export { ZLibStream as ZLibStream } from './System.IO.Compression/internal/index.js';
export { BrotliCompressionOptions as BrotliCompressionOptions } from './System.IO.Compression/internal/index.js';
export { BrotliStream as BrotliStream } from './System.IO.Compression/internal/index.js';
export { BrotliDecoder as BrotliDecoder } from './System.IO.Compression/internal/index.js';
export { BrotliEncoder as BrotliEncoder } from './System.IO.Compression/internal/index.js';
export { ZipFile$instance as ZipFile } from './System.IO.Compression/internal/index.js';
export { ZipFileExtensions$instance as ZipFileExtensions } from './System.IO.Compression/internal/index.js';
