// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Intrinsics
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Runtime.Intrinsics/internal/index.js';

// Cross-namespace type imports for constraints
import type { IAdditionOperators_3, IBitwiseOperators_3, IDivisionOperators_3, IEqualityOperators_3, IMultiplyOperators_3, IShiftOperators_3, ISubtractionOperators_3, IUnaryNegationOperators_2, IUnaryPlusOperators_2, Plane, Quaternion, Vector_1, Vector2, Vector3, Vector4 } from './System.Numerics/internal/index.js';
import type { Boolean as ClrBoolean, Byte, Double, IEquatable_1, Int16, Int32, Int64, IntPtr, MidpointRounding, Object as ClrObject, ReadOnlySpan_1, SByte, Single, Span_1, String as ClrString, Type, UInt16, UInt32, UInt64, UIntPtr, ValueTuple_2, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { Vector128$instance as Vector128_0 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector128_1 as Vector128 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector256$instance as Vector256_0 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector256_1 as Vector256 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector512$instance as Vector512_0 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector512_1 as Vector512 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector64$instance as Vector64_0 } from './System.Runtime.Intrinsics/internal/index.js';
export { Vector64_1 as Vector64 } from './System.Runtime.Intrinsics/internal/index.js';
