// Generated by tsbindgen - Architecture
// Namespace: System.Runtime.Serialization.Json
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace System.Runtime.Serialization.Json in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
