// Generated by tsbindgen - Architecture
// Namespace: System.Security.Policy
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Security.Policy/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection, IEnumerable, IEnumerator } from './System.Collections/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { Evidence as Evidence } from './System.Security.Policy/internal/index.js';
export { EvidenceBase as EvidenceBase } from './System.Security.Policy/internal/index.js';
