// Generated by tsbindgen - Architecture
// Namespace: System.Xml.Serialization
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Xml.Serialization/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable_1, IEnumerator_1 } from './System.Collections.Generic/internal/index.js';
import type { StringCollection } from './System.Collections.Specialized/internal/index.js';
import type { CollectionBase, Hashtable, ICollection, IEnumerable, IEnumerator, IList } from './System.Collections/internal/index.js';
import type { Stream, TextReader, TextWriter } from './System.IO/internal/index.js';
import type { ICustomAttributeProvider, MethodInfo } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { ValidationEventHandler, XmlSchema, XmlSchemaForm } from './System.Xml.Schema/internal/index.js';
import type { WhitespaceHandling, XmlAttribute, XmlElement, XmlNodeType, XmlQualifiedName, XmlReader, XmlWriter } from './System.Xml/internal/index.js';
import type { Array as ClrArray, AsyncCallback, Attribute, Boolean as ClrBoolean, Delegate, Enum, EventArgs, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, IntPtr, ISpanFormattable, MulticastDelegate, Object as ClrObject, String as ClrString, Type, TypeCode, Uri, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CodeGenerationOptions as CodeGenerationOptions } from './System.Xml.Serialization/internal/index.js';
export { CodeIdentifier as CodeIdentifier } from './System.Xml.Serialization/internal/index.js';
export { CodeIdentifiers as CodeIdentifiers } from './System.Xml.Serialization/internal/index.js';
export { ImportContext as ImportContext } from './System.Xml.Serialization/internal/index.js';
export type IXmlSerializable = Internal.IXmlSerializable;
export type IXmlTextParser = Internal.IXmlTextParser;
export { SchemaImporter as SchemaImporter } from './System.Xml.Serialization/internal/index.js';
export { SoapAttributeAttribute as SoapAttributeAttribute } from './System.Xml.Serialization/internal/index.js';
export { SoapAttributeOverrides as SoapAttributeOverrides } from './System.Xml.Serialization/internal/index.js';
export { SoapAttributes as SoapAttributes } from './System.Xml.Serialization/internal/index.js';
export { SoapElementAttribute as SoapElementAttribute } from './System.Xml.Serialization/internal/index.js';
export { SoapEnumAttribute as SoapEnumAttribute } from './System.Xml.Serialization/internal/index.js';
export { SoapIgnoreAttribute as SoapIgnoreAttribute } from './System.Xml.Serialization/internal/index.js';
export { SoapIncludeAttribute as SoapIncludeAttribute } from './System.Xml.Serialization/internal/index.js';
export { SoapReflectionImporter as SoapReflectionImporter } from './System.Xml.Serialization/internal/index.js';
export { SoapSchemaMember as SoapSchemaMember } from './System.Xml.Serialization/internal/index.js';
export { SoapTypeAttribute as SoapTypeAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlAnyAttributeAttribute as XmlAnyAttributeAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlAnyElementAttribute as XmlAnyElementAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlAnyElementAttributes as XmlAnyElementAttributes } from './System.Xml.Serialization/internal/index.js';
export { XmlArrayAttribute as XmlArrayAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlArrayItemAttribute as XmlArrayItemAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlArrayItemAttributes as XmlArrayItemAttributes } from './System.Xml.Serialization/internal/index.js';
export { XmlAttributeAttribute as XmlAttributeAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlAttributeOverrides as XmlAttributeOverrides } from './System.Xml.Serialization/internal/index.js';
export { XmlAttributes as XmlAttributes } from './System.Xml.Serialization/internal/index.js';
export { XmlChoiceIdentifierAttribute as XmlChoiceIdentifierAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlElementAttribute as XmlElementAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlElementAttributes as XmlElementAttributes } from './System.Xml.Serialization/internal/index.js';
export { XmlEnumAttribute as XmlEnumAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlIgnoreAttribute as XmlIgnoreAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlIncludeAttribute as XmlIncludeAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlMappingAccess as XmlMappingAccess } from './System.Xml.Serialization/internal/index.js';
export { XmlMapping as XmlMapping } from './System.Xml.Serialization/internal/index.js';
export { XmlMemberMapping as XmlMemberMapping } from './System.Xml.Serialization/internal/index.js';
export { XmlMembersMapping as XmlMembersMapping } from './System.Xml.Serialization/internal/index.js';
export { XmlNamespaceDeclarationsAttribute as XmlNamespaceDeclarationsAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlReflectionImporter as XmlReflectionImporter } from './System.Xml.Serialization/internal/index.js';
export { XmlReflectionMember as XmlReflectionMember } from './System.Xml.Serialization/internal/index.js';
export { XmlRootAttribute as XmlRootAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlSchemaExporter as XmlSchemaExporter } from './System.Xml.Serialization/internal/index.js';
export { XmlSchemaImporter as XmlSchemaImporter } from './System.Xml.Serialization/internal/index.js';
export { XmlSchemaProviderAttribute as XmlSchemaProviderAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlSchemas as XmlSchemas } from './System.Xml.Serialization/internal/index.js';
export { XmlSchemaEnumerator as XmlSchemaEnumerator } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializationGeneratedCode as XmlSerializationGeneratedCode } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializationReader as XmlSerializationReader } from './System.Xml.Serialization/internal/index.js';
export type XmlSerializationFixupCallback = Internal.XmlSerializationFixupCallback;
export type XmlSerializationCollectionFixupCallback = Internal.XmlSerializationCollectionFixupCallback;
export type XmlSerializationReadCallback = Internal.XmlSerializationReadCallback;
export { XmlSerializationWriter as XmlSerializationWriter } from './System.Xml.Serialization/internal/index.js';
export type XmlSerializationWriteCallback = Internal.XmlSerializationWriteCallback;
export { XmlSerializerAssemblyAttribute as XmlSerializerAssemblyAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlDeserializationEvents as XmlDeserializationEvents } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializerImplementation as XmlSerializerImplementation } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializer as XmlSerializer } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializerFactory as XmlSerializerFactory } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializerNamespaces as XmlSerializerNamespaces } from './System.Xml.Serialization/internal/index.js';
export { XmlSerializerVersionAttribute as XmlSerializerVersionAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlTextAttribute as XmlTextAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlTypeAttribute as XmlTypeAttribute } from './System.Xml.Serialization/internal/index.js';
export { XmlTypeMapping as XmlTypeMapping } from './System.Xml.Serialization/internal/index.js';
export type XmlAttributeEventHandler = Internal.XmlAttributeEventHandler;
export { XmlAttributeEventArgs as XmlAttributeEventArgs } from './System.Xml.Serialization/internal/index.js';
export type XmlElementEventHandler = Internal.XmlElementEventHandler;
export { XmlElementEventArgs as XmlElementEventArgs } from './System.Xml.Serialization/internal/index.js';
export type XmlNodeEventHandler = Internal.XmlNodeEventHandler;
export { XmlNodeEventArgs as XmlNodeEventArgs } from './System.Xml.Serialization/internal/index.js';
export type UnreferencedObjectEventHandler = Internal.UnreferencedObjectEventHandler;
export { UnreferencedObjectEventArgs as UnreferencedObjectEventArgs } from './System.Xml.Serialization/internal/index.js';
