// Generated by tsbindgen - Architecture
// Namespace: System.IO.Pipelines
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.IO.Pipelines/internal/index.js';

// Cross-namespace type imports for constraints
import type { IBufferWriter_1, MemoryPool_1, ReadOnlySequence_1 } from './System.Buffers/internal/index.js';
import type { Stream } from './System.IO/internal/index.js';
import type { Task, ValueTask, ValueTask_1 } from './System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { Action_1, Action_2, Boolean as ClrBoolean, Byte, Exception, Int32, Int64, Memory_1, Object as ClrObject, ReadOnlyMemory_1, SequencePosition, Span_1, String as ClrString, Type, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { FlushResult as FlushResult } from './System.IO.Pipelines/internal/index.js';
export type IDuplexPipe = Internal.IDuplexPipe;
export { Pipe as Pipe } from './System.IO.Pipelines/internal/index.js';
export { PipeOptions as PipeOptions } from './System.IO.Pipelines/internal/index.js';
export { PipeReader as PipeReader } from './System.IO.Pipelines/internal/index.js';
export { PipeScheduler as PipeScheduler } from './System.IO.Pipelines/internal/index.js';
export { PipeWriter as PipeWriter } from './System.IO.Pipelines/internal/index.js';
export { ReadResult as ReadResult } from './System.IO.Pipelines/internal/index.js';
export { StreamPipeExtensions$instance as StreamPipeExtensions } from './System.IO.Pipelines/internal/index.js';
export { StreamPipeReaderOptions as StreamPipeReaderOptions } from './System.IO.Pipelines/internal/index.js';
export { StreamPipeWriterOptions as StreamPipeWriterOptions } from './System.IO.Pipelines/internal/index.js';
