// Generated by tsbindgen - Architecture
// Namespace: System.Runtime
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Runtime/internal/index.js';

// Cross-namespace type imports for constraints
import type { IDictionary } from './System.Collections/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { CriticalFinalizerObject } from './System.Runtime.ConstrainedExecution/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { Action, Attribute, Boolean as ClrBoolean, Enum, Exception, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, String as ClrString, TimeSpan, Type, TypeCode, ValueTuple_2, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ControlledExecution$instance as ControlledExecution } from './System.Runtime/internal/index.js';
export { DependentHandle as DependentHandle } from './System.Runtime/internal/index.js';
export { GCSettings$instance as GCSettings } from './System.Runtime/internal/index.js';
export { JitInfo$instance as JitInfo } from './System.Runtime/internal/index.js';
export { AmbiguousImplementationException as AmbiguousImplementationException } from './System.Runtime/internal/index.js';
export { GCLargeObjectHeapCompactionMode as GCLargeObjectHeapCompactionMode } from './System.Runtime/internal/index.js';
export { GCLatencyMode as GCLatencyMode } from './System.Runtime/internal/index.js';
export { MemoryFailPoint as MemoryFailPoint } from './System.Runtime/internal/index.js';
export { AssemblyTargetedPatchBandAttribute as AssemblyTargetedPatchBandAttribute } from './System.Runtime/internal/index.js';
export { TargetedPatchingOptOutAttribute as TargetedPatchingOptOutAttribute } from './System.Runtime/internal/index.js';
export { ProfileOptimization$instance as ProfileOptimization } from './System.Runtime/internal/index.js';
