// Generated by tsbindgen - Architecture
// Namespace: System.Net.Sockets
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace System.Net.Sockets in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
