// Generated by tsbindgen - Architecture
// Namespace: System.Xml.Xsl.Runtime
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Xml.Xsl.Runtime/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IComparer_1, IEnumerable_1, IEnumerator_1, IList_1 } from './System.Collections.Generic/internal/index.js';
import type { ICollection, IEnumerable, IEnumerator, IList } from './System.Collections/internal/index.js';
import type { Task, ValueTask } from './System.Threading.Tasks/internal/index.js';
import type { XmlAtomicValue, XmlTypeCode } from './System.Xml.Schema/internal/index.js';
import type { XPathItem, XPathNavigator, XPathNodeType } from './System.Xml.XPath/internal/index.js';
import type { WriteState, XmlNameTable, XmlQualifiedName, XmlReader, XmlSpace, XmlWriter, XmlWriterSettings } from './System.Xml/internal/index.js';
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Char, DateTime, DateTimeOffset, Decimal, Double, Enum, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, ISpanFormattable, Object as ClrObject, Single, String as ClrString, TimeSpan, Type, TypeCode, ValueType, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ContentIterator as ContentIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { ElementContentIterator as ElementContentIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { NodeKindContentIterator as NodeKindContentIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { AttributeIterator as AttributeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { NamespaceIterator as NamespaceIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { AttributeContentIterator as AttributeContentIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { ContentMergeIterator as ContentMergeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DodSequenceMerge as DodSequenceMerge } from './System.Xml.Xsl.Runtime/internal/index.js';
export { SetIteratorResult as SetIteratorResult } from './System.Xml.Xsl.Runtime/internal/index.js';
export { UnionIterator as UnionIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { IntersectIterator as IntersectIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DifferenceIterator as DifferenceIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { FollowingSiblingIterator as FollowingSiblingIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { FollowingSiblingMergeIterator as FollowingSiblingMergeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { PrecedingSiblingIterator as PrecedingSiblingIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { PrecedingSiblingDocOrderIterator as PrecedingSiblingDocOrderIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { StringConcat as StringConcat } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DescendantIterator as DescendantIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DescendantMergeIterator as DescendantMergeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { ParentIterator as ParentIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { AncestorIterator as AncestorIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { AncestorDocOrderIterator as AncestorDocOrderIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XPathFollowingIterator as XPathFollowingIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XPathFollowingMergeIterator as XPathFollowingMergeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { PrecedingIterator as PrecedingIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XPathPrecedingIterator as XPathPrecedingIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XPathPrecedingDocOrderIterator as XPathPrecedingDocOrderIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XPathPrecedingMergeIterator as XPathPrecedingMergeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { NodeRangeIterator as NodeRangeIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { Int32Aggregator as Int32Aggregator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { Int64Aggregator as Int64Aggregator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DecimalAggregator as DecimalAggregator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { DoubleAggregator as DoubleAggregator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlCollation as XmlCollation } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlILIndex as XmlILIndex } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlILStorageConverter$instance as XmlILStorageConverter } from './System.Xml.Xsl.Runtime/internal/index.js';
export { IteratorResult as IteratorResult } from './System.Xml.Xsl.Runtime/internal/index.js';
export { IdIterator as IdIterator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlNavigatorFilter as XmlNavigatorFilter } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQueryContext as XmlQueryContext } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQueryOutput as XmlQueryOutput } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQueryRuntime as XmlQueryRuntime } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQuerySequence_1 as XmlQuerySequence } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQueryItemSequence as XmlQueryItemSequence } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlQueryNodeSequence as XmlQueryNodeSequence } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XmlSortKeyAccumulator as XmlSortKeyAccumulator } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XsltConvert$instance as XsltConvert } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XsltFunctions$instance as XsltFunctions } from './System.Xml.Xsl.Runtime/internal/index.js';
export { XsltLibrary as XsltLibrary } from './System.Xml.Xsl.Runtime/internal/index.js';
