// Generated by tsbindgen - Architecture
// Namespace: System.ComponentModel.DataAnnotations
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.ComponentModel.DataAnnotations/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IDictionary_2, IEnumerable_1 } from './System.Collections.Generic/internal/index.js';
import type { IDictionary } from './System.Collections/internal/index.js';
import type { ICustomTypeDescriptor, TypeDescriptionProvider } from './System.ComponentModel/internal/index.js';
import type { MethodBase } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Attribute, Boolean as ClrBoolean, Double, Enum, Exception, Func_2, IComparable, IConvertible, IFormatProvider, IFormattable, Int32, IServiceProvider, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Type, TypeCode, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { AllowedValuesAttribute as AllowedValuesAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { AssociatedMetadataTypeTypeDescriptionProvider as AssociatedMetadataTypeTypeDescriptionProvider } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { AssociationAttribute as AssociationAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { Base64StringAttribute as Base64StringAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { CompareAttribute as CompareAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ConcurrencyCheckAttribute as ConcurrencyCheckAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { CreditCardAttribute as CreditCardAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { CustomValidationAttribute as CustomValidationAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DataType as DataType } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DataTypeAttribute as DataTypeAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DeniedValuesAttribute as DeniedValuesAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DisplayAttribute as DisplayAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DisplayColumnAttribute as DisplayColumnAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { DisplayFormatAttribute as DisplayFormatAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { EditableAttribute as EditableAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { EmailAddressAttribute as EmailAddressAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { EnumDataTypeAttribute as EnumDataTypeAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { FileExtensionsAttribute as FileExtensionsAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { FilterUIHintAttribute as FilterUIHintAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export type IValidatableObject = Internal.IValidatableObject;
export { KeyAttribute as KeyAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { LengthAttribute as LengthAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { MaxLengthAttribute as MaxLengthAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { MetadataTypeAttribute as MetadataTypeAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { MinLengthAttribute as MinLengthAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { PhoneAttribute as PhoneAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { RangeAttribute as RangeAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { RegularExpressionAttribute as RegularExpressionAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { RequiredAttribute as RequiredAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ScaffoldColumnAttribute as ScaffoldColumnAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { StringLengthAttribute as StringLengthAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { TimestampAttribute as TimestampAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { UIHintAttribute as UIHintAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { UrlAttribute as UrlAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ValidationAttribute as ValidationAttribute } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ValidationContext as ValidationContext } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ValidationException as ValidationException } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { ValidationResult as ValidationResult } from './System.ComponentModel.DataAnnotations/internal/index.js';
export { Validator$instance as Validator } from './System.ComponentModel.DataAnnotations/internal/index.js';
