// Generated by tsbindgen - Architecture
// Namespace: System.Dynamic
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Dynamic/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IList_1, KeyValuePair_2 } from './System.Collections.Generic/internal/index.js';
import type { ReadOnlyCollection_1 } from './System.Collections.ObjectModel/internal/index.js';
import type { IEnumerable, IEnumerator } from './System.Collections/internal/index.js';
import type { INotifyPropertyChanged } from './System.ComponentModel/internal/index.js';
import type { Expression, ExpressionType, LabelTarget, ParameterExpression } from './System.Linq.Expressions/internal/index.js';
import type { CallSite_1, CallSiteBinder } from './System.Runtime.CompilerServices/internal/index.js';
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DynamicMetaObjectBinder as DynamicMetaObjectBinder } from './System.Dynamic/internal/index.js';
export { DynamicMetaObject as DynamicMetaObject } from './System.Dynamic/internal/index.js';
export type IDynamicMetaObjectProvider = Internal.IDynamicMetaObjectProvider;
export { BindingRestrictions as BindingRestrictions } from './System.Dynamic/internal/index.js';
export { BinaryOperationBinder as BinaryOperationBinder } from './System.Dynamic/internal/index.js';
export { CallInfo as CallInfo } from './System.Dynamic/internal/index.js';
export { ExpandoObject as ExpandoObject } from './System.Dynamic/internal/index.js';
export { ConvertBinder as ConvertBinder } from './System.Dynamic/internal/index.js';
export { CreateInstanceBinder as CreateInstanceBinder } from './System.Dynamic/internal/index.js';
export { DeleteIndexBinder as DeleteIndexBinder } from './System.Dynamic/internal/index.js';
export { DeleteMemberBinder as DeleteMemberBinder } from './System.Dynamic/internal/index.js';
export { DynamicObject as DynamicObject } from './System.Dynamic/internal/index.js';
export { GetIndexBinder as GetIndexBinder } from './System.Dynamic/internal/index.js';
export { GetMemberBinder as GetMemberBinder } from './System.Dynamic/internal/index.js';
export { InvokeBinder as InvokeBinder } from './System.Dynamic/internal/index.js';
export { InvokeMemberBinder as InvokeMemberBinder } from './System.Dynamic/internal/index.js';
export { SetIndexBinder as SetIndexBinder } from './System.Dynamic/internal/index.js';
export { SetMemberBinder as SetMemberBinder } from './System.Dynamic/internal/index.js';
export { UnaryOperationBinder as UnaryOperationBinder } from './System.Dynamic/internal/index.js';
export type IInvokeOnGetBinder = Internal.IInvokeOnGetBinder;
