// Generated by tsbindgen - Architecture
// Namespace: System.Net.NetworkInformation
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Net.NetworkInformation/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICollection_1, IEnumerable_1, IEnumerator_1 } from './System.Collections.Generic/internal/index.js';
import type { IDictionary, IEnumerable, IEnumerator } from './System.Collections/internal/index.js';
import type { AsyncCompletedEventArgs, Component, IComponent, IContainer, ISite, Win32Exception } from './System.ComponentModel/internal/index.js';
import type { IPAddress, IPEndPoint } from './System.Net/internal/index.js';
import type { MethodBase, MethodInfo } from './System.Reflection/internal/index.js';
import type { ISerializable, SerializationInfo, StreamingContext } from './System.Runtime.Serialization/internal/index.js';
import type { Task_1 } from './System.Threading.Tasks/internal/index.js';
import type { CancellationToken } from './System.Threading/internal/index.js';
import type { AsyncCallback, Boolean as ClrBoolean, Byte, Char, Delegate, Enum, EventArgs, Exception, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormatProvider, IFormattable, Int32, Int64, IntPtr, InvalidOperationException, ISpanFormattable, MulticastDelegate, Object as ClrObject, ReadOnlySpan_1, String as ClrString, TimeSpan, Type, TypeCode, Void } from './System/internal/index.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { DuplicateAddressDetectionState as DuplicateAddressDetectionState } from './System.Net.NetworkInformation/internal/index.js';
export { GatewayIPAddressInformation as GatewayIPAddressInformation } from './System.Net.NetworkInformation/internal/index.js';
export { GatewayIPAddressInformationCollection as GatewayIPAddressInformationCollection } from './System.Net.NetworkInformation/internal/index.js';
export { IcmpV4Statistics as IcmpV4Statistics } from './System.Net.NetworkInformation/internal/index.js';
export { IcmpV6Statistics as IcmpV6Statistics } from './System.Net.NetworkInformation/internal/index.js';
export { IPAddressInformation as IPAddressInformation } from './System.Net.NetworkInformation/internal/index.js';
export { IPAddressInformationCollection as IPAddressInformationCollection } from './System.Net.NetworkInformation/internal/index.js';
export { IPGlobalProperties as IPGlobalProperties } from './System.Net.NetworkInformation/internal/index.js';
export { IPGlobalStatistics as IPGlobalStatistics } from './System.Net.NetworkInformation/internal/index.js';
export { IPInterfaceProperties as IPInterfaceProperties } from './System.Net.NetworkInformation/internal/index.js';
export { IPInterfaceStatistics as IPInterfaceStatistics } from './System.Net.NetworkInformation/internal/index.js';
export { IPv4InterfaceProperties as IPv4InterfaceProperties } from './System.Net.NetworkInformation/internal/index.js';
export { IPv4InterfaceStatistics as IPv4InterfaceStatistics } from './System.Net.NetworkInformation/internal/index.js';
export { IPv6InterfaceProperties as IPv6InterfaceProperties } from './System.Net.NetworkInformation/internal/index.js';
export { MulticastIPAddressInformation as MulticastIPAddressInformation } from './System.Net.NetworkInformation/internal/index.js';
export { MulticastIPAddressInformationCollection as MulticastIPAddressInformationCollection } from './System.Net.NetworkInformation/internal/index.js';
export { NetBiosNodeType as NetBiosNodeType } from './System.Net.NetworkInformation/internal/index.js';
export { NetworkChange as NetworkChange } from './System.Net.NetworkInformation/internal/index.js';
export { NetworkAvailabilityEventArgs as NetworkAvailabilityEventArgs } from './System.Net.NetworkInformation/internal/index.js';
export type NetworkAddressChangedEventHandler = Internal.NetworkAddressChangedEventHandler;
export type NetworkAvailabilityChangedEventHandler = Internal.NetworkAvailabilityChangedEventHandler;
export { NetworkInterface as NetworkInterface } from './System.Net.NetworkInformation/internal/index.js';
export { NetworkInterfaceComponent as NetworkInterfaceComponent } from './System.Net.NetworkInformation/internal/index.js';
export { NetworkInterfaceType as NetworkInterfaceType } from './System.Net.NetworkInformation/internal/index.js';
export { OperationalStatus as OperationalStatus } from './System.Net.NetworkInformation/internal/index.js';
export { PhysicalAddress as PhysicalAddress } from './System.Net.NetworkInformation/internal/index.js';
export { PrefixOrigin as PrefixOrigin } from './System.Net.NetworkInformation/internal/index.js';
export { ScopeLevel as ScopeLevel } from './System.Net.NetworkInformation/internal/index.js';
export { SuffixOrigin as SuffixOrigin } from './System.Net.NetworkInformation/internal/index.js';
export { TcpConnectionInformation as TcpConnectionInformation } from './System.Net.NetworkInformation/internal/index.js';
export { TcpState as TcpState } from './System.Net.NetworkInformation/internal/index.js';
export { TcpStatistics as TcpStatistics } from './System.Net.NetworkInformation/internal/index.js';
export { UdpStatistics as UdpStatistics } from './System.Net.NetworkInformation/internal/index.js';
export { UnicastIPAddressInformation as UnicastIPAddressInformation } from './System.Net.NetworkInformation/internal/index.js';
export { UnicastIPAddressInformationCollection as UnicastIPAddressInformationCollection } from './System.Net.NetworkInformation/internal/index.js';
export { NetworkInformationException as NetworkInformationException } from './System.Net.NetworkInformation/internal/index.js';
export { IPStatus as IPStatus } from './System.Net.NetworkInformation/internal/index.js';
export { Ping as Ping } from './System.Net.NetworkInformation/internal/index.js';
export type PingCompletedEventHandler = Internal.PingCompletedEventHandler;
export { PingCompletedEventArgs as PingCompletedEventArgs } from './System.Net.NetworkInformation/internal/index.js';
export { PingException as PingException } from './System.Net.NetworkInformation/internal/index.js';
export { PingOptions as PingOptions } from './System.Net.NetworkInformation/internal/index.js';
export { PingReply as PingReply } from './System.Net.NetworkInformation/internal/index.js';
export { IPAddressCollection as IPAddressCollection } from './System.Net.NetworkInformation/internal/index.js';
