// Generated by tsbindgen - Architecture
// Namespace: System.Text.Json.Schema
// Assembly: System.Text.Json

// Branded primitive types are sourced from @tsonic/types
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/types';

// Import types from other namespaces
import type { JsonNode } from "../../System.Text.Json.Nodes/internal/index.js";
import type { JsonPropertyInfo, JsonTypeInfo } from "../../System.Text.Json.Serialization.Metadata/internal/index.js";
import type { JsonSerializerOptions } from "../../System.Text.Json/internal/index.js";
import * as System_Internal from "../../System/internal/index.js";
import type { Boolean as ClrBoolean, Func_3, Int32, Object as ClrObject, ReadOnlySpan_1, String as ClrString, Type, ValueType } from "../../System/internal/index.js";

// CLROf<T> - Maps ergonomic primitives to their CLR types for generic constraints
// This utility is used ONLY in generic type arguments to satisfy CLR interface constraints
// Value positions (parameters, return types) use lowercase primitives for ergonomics
export type CLROf<T> =
    T extends sbyte ? System_Internal.SByte :
    T extends short ? System_Internal.Int16 :
    T extends int ? System_Internal.Int32 :
    T extends long ? System_Internal.Int64 :
    T extends int128 ? System_Internal.Int128 :
    T extends nint ? System_Internal.IntPtr :
    T extends byte ? System_Internal.Byte :
    T extends ushort ? System_Internal.UInt16 :
    T extends uint ? System_Internal.UInt32 :
    T extends ulong ? System_Internal.UInt64 :
    T extends uint128 ? System_Internal.UInt128 :
    T extends nuint ? System_Internal.UIntPtr :
    T extends half ? System_Internal.Half :
    T extends float ? System_Internal.Single :
    T extends double ? System_Internal.Double :
    T extends decimal ? System_Internal.Decimal :
    T extends char ? System_Internal.Char :
    T extends boolean ? System_Internal.Boolean :
    T extends string ? System_Internal.String :
    T; // Identity fallback for non-primitive types

export interface JsonSchemaExporterContext$instance {
    readonly baseTypeInfo: JsonTypeInfo;
    readonly path: ReadOnlySpan_1<CLROf<string>>;
    readonly propertyInfo: JsonPropertyInfo;
    readonly typeInfo: JsonTypeInfo;
}


export const JsonSchemaExporterContext: {
    new(): JsonSchemaExporterContext$instance;
};


export type JsonSchemaExporterContext = JsonSchemaExporterContext$instance;

export interface JsonSchemaExporterOptions$instance {
    transformSchemaNode: Func_3<JsonSchemaExporterContext, JsonNode, JsonNode>;
    treatNullObliviousAsNonNullable: boolean;
}


export const JsonSchemaExporterOptions: {
    new(): JsonSchemaExporterOptions$instance;
    readonly default_: JsonSchemaExporterOptions;
};


export type JsonSchemaExporterOptions = JsonSchemaExporterOptions$instance;

export abstract class JsonSchemaExporter$instance {
    static getJsonSchemaAsNode(options: JsonSerializerOptions, type_: Type, exporterOptions?: JsonSchemaExporterOptions): JsonNode;
    static getJsonSchemaAsNode(typeInfo: JsonTypeInfo, exporterOptions?: JsonSchemaExporterOptions): JsonNode;
}


export type JsonSchemaExporter = JsonSchemaExporter$instance;

